extends: debug_esd_cityscapes.yaml
experiment:
  name: dfm_debug_ddp_stage2_csd
  output_dir: /home/igarashi_25/playground_2/CSDFM/DFM/results/debug_ddp_stage2_csd
training:
  batch_size: 4
evaluation:
  batch_size: 4
loss:
  consistency:
    type: csd
wandb:
  name: debug-ddp-stage2-csd
  tags: [debug, ddp, stage2, csd]
