extends: debug_ddp_stage2_psd.yaml
experiment:
  name: dfm_debug_ddp_joint_psd
  output_dir: /home/igarashi_25/playground_2/CSDFM/DFM/results/debug_ddp_joint_psd
  stage: joint_training
checkpoint:
  init_from: null
  resume: null
wandb:
  name: debug-ddp-joint-psd
  tags: [debug, ddp, joint, psd]
